name: Integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  BOA_FORK_RPC_URL: ${{ secrets.BOA_FORK_RPC_URL }}
  BOA_FORK_NO_CACHE: "TRUE"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: make install-dev

    - name: Run project integration tests
      run: make integration-tests
